name: py313_lwreg
channels:
  - conda-forge
dependencies:
  - python=3.13
  - rdkit >=2024.09.1
  - ipython
  - jupyter
  - jupysql
  - sqlalchemy
  - pytest
  - tqdm
  - click
  # the next two are only required if you want to use postgresql
  - psycopg
  - openssl=3.4