name: py311_lwreg
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit >=2023.03.1
  - ipython
  - jupyter
  - ipython-sql
  - sqlalchemy
  - pytest
  - tqdm
  - click
  # the next two are only required if you want to use postgresql
  - psycopg
  - openssl=3.4